language: ruby
cache: bundler
branches:
  only:
  - gh-pages
  - /.*/
rvm:
  - 2.6.3
  - 2.6.6
  - 2.7.1
matrix:
  allow_failures:
    - rvm: 2.6.3
    - rvm: 2.6.6
  fast_finish: true
install:
  - travis_retry bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --assume-extension --check-favicon --check-html --allow-hash-href --empty-alt-ignore --http-status-ignore "400, 403, 409, 429"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
