# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

theme:            "minimal-mistakes-jekyll"
minimal_mistakes_skin:   "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


# Site Settings
locale                   : "da"
title                    : "Vejle Idrætsskolers Fond"
title_separator          : "-"
subtitle                 : "Støt udviklingen af Vejle Idrætshøjskole og Vejle Idrætsefterskole"
name                     : "Vejle Idrætsskolers Fond"
description              : "Vejle Idrætsskolers Fond er at støtte udviklingen af Vejle Idrætshøjskoles og Idrætsefterskoles faciliteter."
logo                     : "/android-chrome-192x192.png"
url                      : "https://fond.vih.dk" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
email                    : "kontor@vih.dk"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "vih/fond-jekyll" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : false # "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            : ""
staticman:
  branch                 : ""
atom_feed:
  path                   : # blank (default) uses feed.xml


# reCaptcha
# Register your domain at https://www.google.com/recaptcha/ and choose reCAPTCHA V2
# reCaptcha:
#  enabled: true
#  siteKey: "6LdCtVoUAAAAADcxG1WekIUuEuJy3YPoQ8DtbzK8"
#  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
#  # For more information, https://staticman.net/docs/encryption
#  secret: "B6TmweBhBmEXsUUZKFEXOuFbAOHGBluvOCpsyTzAR+jjB5IkDNXzQo2NmMt8alWLWHh1HentKbOWAOx7HCl7AH3qgSeGWIvaTV99lKC8IakuyWGd2ZJR+eGxqN5RbmiNA1e4NXT4Z3DEMzq89iM/1VFkjSOY+LqAtWkdpJQTIGQ="


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               : "google-universal" # false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-4137620-4"


# Social Sharing
twitter:
  username               : "vihdk"
facebook:
  username               : "vihdk"
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


footer:
  links:
    - label: "Vejle Idrætshøjskole"
      url: "https://www.vih.dk"
      icon: "fas fa-fw fa-globe"
    - label: "Vejle Idrætsefterskole"
      url: "https://www.vies.dk"
      icon: "fas fa-fw fa-globe"
    - label: "Privatlivspolitik"
      url: "/privatlivspolitik/"
      icon: "fas fa-fw fas fa-user-shield"
    - label: "Ørnebjergvej 28, 7100 Vejle"
      icon: "fas fa-fw fa-envelope"
      url: "/kontakt/"


# Site Author
author:
  name: "Vejle Idrætsskolers Fond"
  bio: "Vejle Idrætsskolers Fonds formål er at understøtte Vejle Idrætshøjskoles og Vejle Idrætsefterskoles udvikling - og skabe flere drømmestunder på skolerne og gøre det muligt, at skolerne gør en forskel i verden."
  avatar: "/android-chrome-192x192.png"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kontor@vih.dk"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
github: [metadata]


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-include-cache


# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Add custom collections
collections:
  pages:
    output: true


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: false
