backend:
  name: github
  repo: vih/fond-jekyll
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Category", name: "category", widget: "select", options: ["Status", "Nybyggeri", "Renovering", "Nyhedsbrev"], multiple: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "intro", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
